apiVersion: v1
kind: Service
metadata:
  name: wordpress # 생성할 서비스의 이름
  namespace: test-wordpress # 생성한 네임스페이스 입력
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer # 외부로 서비스 노출을 위해 LoadBalancer 혹은 NodePort중 선택
