apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql # DB_HOST 입력
  namespace: test-wordpress # 생성한 네임스페이스 입력
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
