apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim # 생성될 PVC 이름 입력
  namespace: test-wordpress # 생성한 네임스페이스 입력
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce # ReadWriteOnce와 ReadWriteMany중 선택
    # ReadWriteOnce -- 하나의 노드에서 볼륨을 읽기-쓰기로 마운트 가능 (RWO)
    # ReadOnlyMany -- 여러 노드에서 볼륨을 읽기 전용으로 마운트 가능 (ROX)
    # ReadWriteMany -- 여러 노드에서 볼륨을 읽기-쓰기로 마운트 가능 (RWX)
  resources:
    requests:
      storage: 20Gi # 할당할 용량 입력
      # 생성 이후 증가는 가능하나 축소는 불가능
